language: java
sudo: required
addons:
  ulimit:
    nofile: 1048576
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script: "./gradlew clean test jar"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LrE9s80gBkXFoiEu0+8UuFvzA8/k1H4JbCkIzFerpmSmNbs2mi5LNHiixhSR46XcizPd76+uYg8vYv0X9vMq+bbmB/dThpZDxCrpwuEK+WQ3VUtZJPG4QN5u29mzW53UAQ8qC088twDm1/hdc/3OhHx3557acndC8PyeUvK4JtuTplC8hijru9E2nFd6m8ewZFNBQt5Co6Ajqj22670Ij161/v3oDLz55DmFGB8ojvzaUUVWdYq7JV9hQ9vwC6Q5HI8XtHGyzjMU+ngi5t6S6PfPGsghORoXQti0eORpug66/1Ku66BS2QmVqiTK/LP/u1scP8esXMTQNyiJSTWoPvkpVlVtaZtGNQJ4VM3RGggtCzjQmklSUEfDuw4ricrS6hxuvU+dzBtpmxHLjJdRJ4Zq0hs4Dr+erO1BJ4Cr1LXKPH8a0uK7IdOU/fe5aFGTI4C54mxNc9319c3sB3opdvKHmOdjdG4oBJ8a4WYS4GAxS2xmvY7RZz3aVUgITrerzYxUUIOP9m/1BwekUcQjKA2qi5dDPZe01QsQcTrqfxtV/bemCDOS7huqAEm/lSFI9KKzUBqx9w/NG5qL4tMesTQ7AdBmFUiM6M2u3yug+rCA2XTpafZcvVwOwqdoQMA4cvV4ch9tWzVL8AyEW8A8XHmNa+hvVZYX+eaN7Atj6Po=
  file: "./build/libs/mongoose-storage-driver-swift.jar"
  on:
    tags: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "XxcZY/4wyPMki7hOcU8UIJIaLi+RmQtUxtNgsA5LJfEld6ty7HMPoFwHrGKT48vWxNFzYoUy8dyjQvSiox1aAcfEt9+5U++rmbx73mQt/h54JFlNkrjmpw1zfL5AUXnmrn2ymGdmP4FRB6mDW8MQgSQSTB2+H1IrlbhrK5+74qKGbNIC/w6EE0gLhI53mk4rLrVahAtsfu0BZm/dLGskKR0S2GXVPNPZShhpdyZPwwDddo0iu/TlMWdKPJlLJ1m7pDK0aTdfHv9nNTHqylK/LCXLEQ8iLQQK18sZSEWaAeovCn46GxeaOyk2+U8sMAyOsrqZwX0m+wskT3Q7LXSL3Zskt2JmRTBxFsZC7FFDoeeGEZmPb35U4j2tQNKfS10RAvcrZQijhhRkCjMs0nky4g4CQP5Ny5f5+BuoVVHsrBSFSyFkIghV3JwYUrl2FcxY8ccxYUAgHIbbqUmc/nBQpjKEpNhmNEu5eFhetDb1beCEeFEyZ97aCA1q6djjxIrDKAcTIM0rbjCKt7aUm16bH9Qze2M+pwyO8Om1tReAefujFp6yF/zmpqLR6f0RIxlKqiSb+uq2aW4HezGXsxgne9KZ2lyLgBsTkNRGebgEvwpy4+QIeAXd33lyoO8xg/JeJTMLvPZg3eF+Lx7mXuwiEo63UdfXm8Buh9i+keREBsQ="
  - secure: "Td+5aNOIfV+CjgCRq7WK8+RGjLEDmrqTyV5U/tvWX99IzWGZsdgDiYAxwagDnc13ywbgW5avqqnjrwWI9ZW/obpVTZ7PE5LGs1DbUZuR8OksF+gTT74l0F3KCqbI0B+YYneQcR0mCrruJcLWtiWqpQRKm1eREnnE+fYQuoydUEgMYOc/M8urabxcGBRA6jENeXyjeByUmvUzcDo8dWov3eWwTkx5SI/tO8zL+IUVlbH8f6Zc2ogjJ8PfN89KIYmAEba2PkR9M6CITZkxkOOPfNVidLiWnp8xT44Oai69NU7uIOum7ljUC6mG/VUpnJv8q69aGb6QzoWlByqI4LpLtRDiP9g6WXzSRGkmq9bQABM32UNDFTOQ4te+LLWEsIAVsfBU5AJDc5JjfGdWmSj8fwQpUV7TuPtpD8mMZlZW7dtP14ZLQwa4gfSjXIPMDxSEqLj280NzRFIFe2nqRtjg8PAFmvr3xh5Q4OEIkrOTBPmU6d3knqw0q6gc9mJN+4xzNU/d9Ho0TbLwLfdppT/M2UjfxT9syZioSjQWG9KlAZGuNEvLW0DW7mMEdFWxLIQ0jqcRJbDSEk/3d7DM7jzBKcWKhnMW7tbPfb0fRAdTV4dSUZikDok8xZeEM5QZ5fkF3iAbG5TSs3oy+nIxX8+qGrSTzrhF0OQxrUkGqakB6QU="
after_success:
- echo $DOCKER_PASS
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=emcmongoose/mongoose-storage-driver-swift
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build --build-arg MONGOOSE_VERSION=latest -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- export REPO=emcmongoose/mongoose-storage-driver-service-swift
- docker build --build-arg MONGOOSE_VERSION=latest -f docker/Dockerfile.storage-driver-service -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
